Procesador=ProcesadorYodafy
Servidor=YodafyServidorIterativo
Cliente=YodafyClienteTCP

servidor:
	javac $(Servidor).java
	java $(Servidor)
	
cliente: 
	javac $(Cliente).java
	java $(Cliente)

clean:
	rm -f *.class
