Procesador=ProcesadorYodafyTexto
Servidor=YodafyServidorIterativoTexto
Cliente=YodafyClienteTCPTexto

servidor:
	javac $(Servidor).java
	java $(Servidor)
	
cliente: 
	javac $(Cliente).java
	java $(Cliente)

clean:
	rm -f *.class
